import Head from "next/head";
import Image from "next/image";
import Login from "../components/login";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";

export default function Home() {
const {isAuthenticated} = useMoralis();
console.log(isAuthenticated.valueOf());

if (!isAuthenticated) {return   <Login />}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      hii
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
